// import { Product } from './store';

// export const initialProducts: Product[] = [
//   {
//     id: '1',
//     name: 'Wireless Headphones',
//     price: 299.99,
//     image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
//     description: 'Premium wireless headphones with noise cancellation and superior sound quality.',
//     category: 'Electronics',
//     rating: 4.5,
//     reviews: [
//       {
//         id: '1',
//         productId: '1',
//         userName: 'John Doe',
//         rating: 5,
//         comment: 'Amazing sound quality!',
//         date: '2024-01-15',
//       },
//       {
//         id: '2',
//         productId: '1',
//         userName: 'Jane Smith',
//         rating: 4,
//         comment: 'Great headphones, comfortable to wear.',
//         date: '2024-01-10',
//       },
//     ],
//     stock: 50,
//   },
//   {
//     id: '2',
//     name: 'Smart Watch',
//     price: 399.99,
//     image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
//     description: 'Advanced smartwatch with fitness tracking and health monitoring features.',
//     category: 'Electronics',
//     rating: 4.3,
//     reviews: [
//       {
//         id: '3',
//         productId: '2',
//         userName: 'Mike Johnson',
//         rating: 4,
//         comment: 'Good battery life and features.',
//         date: '2024-01-12',
//       },
//     ],
//     stock: 30,
//   },
//   {
//     id: '3',
//     name: 'Laptop Backpack',
//     price: 79.99,
//     image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
//     description: 'Durable laptop backpack with multiple compartments and water-resistant material.',
//     category: 'Accessories',
//     rating: 4.7,
//     reviews: [],
//     stock: 100,
//   },
//   {
//     id: '4',
//     name: 'Bluetooth Speaker',
//     price: 149.99,
//     image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop',
//     description: 'Portable Bluetooth speaker with 360-degree sound and waterproof design.',
//     category: 'Electronics',
//     rating: 4.4,
//     reviews: [],
//     stock: 75,
//   },
//   {
//     id: '5',
//     name: 'Gaming Mouse',
//     price: 89.99,
//     image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&h=500&fit=crop',
//     description: 'High-precision gaming mouse with customizable RGB lighting and programmable buttons.',
//     category: 'Gaming',
//     rating: 4.6,
//     reviews: [],
//     stock: 60,
//   },
//   {
//     id: '6',
//     name: 'Wireless Charger',
//     price: 49.99,
//     image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=500&h=500&fit=crop',
//     description: 'Fast wireless charging pad compatible with all Qi-enabled devices.',
//     category: 'Accessories',
//     rating: 4.2,
//     reviews: [],
//     stock: 120,
//   },
// ];